#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your windows manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xset -b

# Start gnome-keyring
eval $(/usr/bin/gnome-keyring-daemon --start -l --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

exec dbus-launch $HOME/.Xsession

