#!/bin/sh

APPNAME="PaYap"
PAYAPDIR="/home/olivaa/.payap"
COMMAND="$PAYAPDIR/command"

notify()
{
    notify-send --expire-time=1000 --urgency="$1" --app-name="$APPNAME" --category="device" "$2" "$3"
}

toggle_volume()
{
    echo toggle > "$COMMAND"
    notify normal "Card $(cat "$PAYAPDIR/default_sink")" "$(cat "$PAYAPDIR/volume")"
}

up_volume()
{
    echo up > "$COMMAND"
    notify normal "Card $(cat "$PAYAPDIR/default_sink")" "$(cat "$PAYAPDIR/volume")"
}

down_volume()
{
    echo down > "$COMMAND"
    notify normal "Card $(cat "$PAYAPDIR/default_sink")" "$(cat "$PAYAPDIR/volume")"
}

switch_sink()
{
    echo switch > "$COMMAND"
    notify normal "Card $(cat "$PAYAPDIR/default_sink")" "$(cat "$PAYAPDIR/volume")"
}

case $1 in
    "toggle")
        toggle_volume
        ;;
    "up")
        up_volume
        ;;
    "down")
        down_volume
        ;;
    "select")
        switch_sink
        ;;
    *)
esac
