# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle :compinstall filename '/home/olivaa/.zshrc'

autoload -Uz compinit
autoload -U colors && colors
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install

# Load aliases
source  /home/olivaa/.aliases

# Export some env vars
export EDITOR=vim


# Load path to zsh functions
fpath=($fpath $HOME/.zsh/func)
typeset -U fpath
# Set general path
path=($path $HOME/.bin/ /opt/)

# Prompt theme
setopt promptsubst
autoload -U promptinit
promptinit
prompt yapbreak

